HAI
CAN HAS STDIO?
I HAS A WALL
LOL WALL R 99
IM IN YR CODE
  IZ WALL SMALR THAN 1?
         VISIBLE "0 BEERZORZ ON WALL. OH NOEZ!!1". GTFO
  KTHX
  VISIBLE WALL!
  VISIBLE " BEERZORZ ON WALL. LOL!!1"
  NERFZ WALL!!
KTHX
KTHXBYE
