HAI
I HAS A VAR1, I HAS A VAR2
GIMMEH VAR1, GIMMEH VAR2

VISIBLE ":[COPYRIGHT SIGN] Me, Now."

VISIBLE "SUM:: " SUM OF VAR1 AN VAR2
VISIBLE "DIFF:: " DIFF OF VAR1 AN VAR2
VISIBLE "PRODUKT:: " PRODUKT OF VAR1 AN VAR2
VISIBLE "QUOSHUNT:: " QUOSHUNT OF VAR1 AN VAR2
VISIBLE "MOD:: " MOD OF VAR1 AN VAR2
VISIBLE "BIGGR:: " BIGGR OF VAR1 AN VAR2
VISIBLE "SMALLR:: " SMALLR OF VAR1 AN VAR2

KTHXBYE
